services:
    lpi_lucene.search:
        class: Lpi\Bundle\SearchBundle\Service\SearchService
        arguments: [@ivory_lucene_search]
    lpi_lucene.index_command:
        class: Lpi\Bundle\SearchBundle\Command\IndexationCommand
        arguments:
            - "sample-sitemap.xml"
        tags:
            - { name: console.command }
